export const LOGIN_REQ = "LOGIN_REQ"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const REGISTER_REQ = "REGISTER_REQ"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const LOGOUT = "LOGOUT"
