

export const GET_MEN_DATA_REQ = "GET_MEN_DATA_REQ"
export const GET_MEN_DATA_SUCCESS = "GET_MEN_DATA_SUCCESS"
export const GET_MEN_DATA_FAIL = "GET_MEN_DATA_FAIL"

export const GET_MEN_SINGLE_DATA_REQ = "GET_MEN_SINGLE_DATA_REQ"
export const GET_MEN_SINGLE_DATA_SUCCESS = "GET_MEN_SINGLE_DATA_SUCCESS"
export const GET_MEN_SINGLE_DATA_FAIL = "GET_MEN_SINGLE_DATA_FAIL"

export const GET_WOMEN_DATA_REQ = "GET_WOMEN_DATA_REQ"
export const GET_WOMEN_DATA_SUCCESS = "GET_WOMEN_DATA_SUCCESS"
export const GET_WOMEN_DATA_FAIL = "GET_WOMEN_DATA_FAIL"

export const GET_WOMEN_SINGLE_DATA_REQ = "GET_WOMEN_SINGLE_DATA_REQ"
export const GET_WOMEN_SINGLE_DATA_SUCCESS = "GET_WOMEN_SINGLE_DATA_SUCCESS"
export const GET_WOMEN_SINGLE_DATA_FAIL = "GET_WOMEN_SINGLE_DATA_FAIL"

export const SENT_TO_CART = "SENT_TO_CART"
export const GET_DATA_FROM_CART = "GET_DATA_FROM_CART"

export const SEND_PAYMENT_DATA = "SEND_PAYMENT_DATA"
export const GET_PAYMENT_DATA = "GET_PAYMENT_DATA"
