export const SEND_DATA_REQ = "SEND_DATA_REQ"
export const SEND_DATA_SUCCESS = "SEND_DATA_SUCCESS"
export const SEND_DATA_FAIL = "SEND_DATA_FAIL"


export const GET_MEN_DATA_REQ = "GET_MEN_DATA_REQ"
export const GET_MEN_DATA_SUCCESS = "GET_MEN_DATA_SUCCESS"
export const GET_MEN_DATA_FAIL = "GET_MEN_DATA_FAIL"

export const GET_MEN_SINGLE_DATA_REQ = "GET_MEN_SINGLE_DATA_REQ"
export const GET_MEN_SINGLE_DATA_SUCCESS = "GET_MEN_SINGLE_DATA_SUCCESS"
export const GET_MEN_SINGLE_DATA_FAIL = "GET_MEN_SINGLE_DATA_FAIL"

export const GET_WOMEN_DATA_REQ = "GET_WOMEN_DATA_REQ"
export const GET_WOMEN_DATA_SUCCESS = "GET_WOMEN_DATA_SUCCESS"
export const GET_WOMEN_DATA_FAIL = "GET_WOMEN_DATA_FAIL"

export const GET_WOMEN_SINGLE_DATA_REQ = "GET_WOMEN_SINGLE_DATA_REQ"
export const GET_WOMEN_SINGLE_DATA_SUCCESS = "GET_WOMEN_SINGLE_DATA_SUCCESS"
export const GET_WOMEN_SINGLE_DATA_FAIL = "GET_WOMEN_SINGLE_DATA_FAIL"


export const SENT_TO_CART = "SENT_TO_CART"

export const GET_DATA_FROM_CART = "GET_DATA_FROM_CART"