export const SEND_DATA_REQ = "SEND_DATA_REQ"
export const SEND_DATA_SUCCESS = "SEND_DATA_SUCCESS"
export const SEND_DATA_FAIL = "SEND_DATA_FAIL"


export const GET_DATA_REQ = "GET_DATA_REQ"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FAIL = "GET_DATA_FAIL"


export const GET_SINGLE_DATA_REQ = "GET_SINGLE_DATA_REQ"
export const GET_SINGLE_DATA_SUCCESS = "GET_SINGLE_DATA_SUCCESS"
export const GET_SINGLE_DATA_FAIL = "GET_SINGLE_DATA_FAIL"
